### ISSUE TITLE
Additional instances for the Render class

### ISSUE THREAD

**Issue by carlosdagos** [oprdyn/unbeliever#7]
I think the following instances would come in handy if they were implemented by default:

- `Render String`
- `Render Text`
- `ToJSON a => Render a`

Worth a thought 😄

Thanks!

**Comment by afcowie** [comment]
I implemented String and Text no problem, but how do you do the third one? Last night I tried:

```haskell
instance Aeson.ToJSON a => Render a where
    type Token a = JsonToken
    colourize = colourizeJson
    intoDocA = prettyValue  . Aeson.toJSON
```

and although that requires

```
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE UndecidableInstances #-}
```
(er, ok, does that matter?) it still fails because the type family

```haskell
    type Token a = JsonToken
```

is going to match (that is, conflict with) everything, conflicting with every other Render instance we have. Sure enough, it does not compile:

```text
lib/Core/Encoding/Json.hs:260:10-14: error:
    Conflicting family instance declarations:
      Token a = JsonToken -- Defined at lib/Core/Encoding/Json.hs:260:10
      Token Bytes = () -- Defined at lib/Core/Text/Bytes.hs:118:10
    |
260 |     type Token a = JsonToken
    |          ^^^^^
``` 
Yup. Two conflicting definitions. For once the GHC error messages makes sense.

**Comment by carlosdagos** [comment]
Thanks for the update :)

I guess it'd be just as good to just do, say `Render JsonValue` or `Render Aeson.Value` (or both?).

This way users would do

```haskell
debugR "data in json" $ encode data
```

Which looks quite all right, imo.
